# Generated by Django 2.0.4 on 2018-04-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_logininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todolist_name', models.TextField(max_length=100)),
                ('todolist_due_date', models.DateField()),
                ('todolist_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todolistitem_owner', models.CharField(max_length=100)),
                ('todolistitem_name', models.CharField(max_length=100)),
                ('todolistitem_status', models.BooleanField(default=False)),
                ('todolistitem_deadline', models.DateField()),
                ('todolistitem_description', models.TextField()),
                ('todolistitem_createdate', models.DateField()),
                ('todolistitem_updatedate', models.DateField()),
                ('todolist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.ToDoList')),
            ],
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='todolist',
            name='todolist_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.LoginInfo'),
        ),
    ]
