# Generated by Django 2.0.4 on 2018-04-29 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20180429_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='edited_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
